### PR TITLE
Flag for skipping the test is added

### PR DESCRIPTION
**Pull request by nishith-vihar**
when 'skip-test' comment is added in the test case then
that particular test case is skipped and is not executed

Fixes: #207
Signed-off-by: Nishith Vihar Sakinala <nsakinal@redhat.com>

### CODE REVIEW

**Comment by BarakSason** [comment]
Can you please clarify under what circumstances we'd want to add a 'skip-test' comment to the test?

**Comment by nishith-vihar** [comment]
I think we can use it in cases where we would want to skip 1 or 2 test cases or some test cases related to a particular component due to some bug which may not be corrected immediately and we want to test all other test cases.

**Comment by nik-redhat** [comment]
Similar to the use of `flaky` in our `.t` tests.

**Comment by BarakSason** [comment]
> Similar to the use of `flaky` in our `.t` tests.

That's exactly why I'm not of this - If there's a problem, this problem needs to be fixed, not ignored and "hidden" someplace no one will find, or care about.

> I think we can use it in cases where we would want to skip 1 or 2 test cases or some test cases related to a particular component due to some bug which may not be corrected immediately and we want to test all other test cases.

This takes things from another view.
If a given test was working fine up until now, and due to some recent change is now failing, what's the point of just ignoring this failure? The whole point is to prevent regression.
If this test was failing from the start (due to an actual bug in the product), this test shouldn't be merged until the product itself is fixed.

IMO, the only case when tests needs to be skipped is if the config provided by the user cannot satisfy this particular tests requirements (e,g, the test MUST HAVE 10 servers to operate, but the environment only contains 5).

**Comment by nik-redhat** [comment]
> That's exactly why I'm not of this - If there's a problem, this problem needs to be fixed, not ignored and "hidden" someplace no one will find, or care about.
> 
> This takes things from another view.
> If a given test was working fine up until now, and due to some recent change (in the product's code) is now failing, what's the point of just ignoring this failure? The whole point is to prevent regression.

The thing is sometimes it's not easy to fix few failures and that might cause some delay, and if due to a particular test that might not hold much importance (or even if it does), should the whole pipeline be blocked? IMO I don't think that's valid.

> If this test was failing from the start (due to an actual bug in the product), this test shouldn't be merged until the product itself is fixed.

That I think is a different scenario.

> 
> IMO, the only case when tests needs to be skipped is if the config provided by the user cannot satisfy this particular tests requirements (e.g. the test MUST HAVE 10 servers to operate, but the environment only contains 5).

This is a good case, but not the only possible reason for this feature AFAIT.

**Comment by srijan-sivakumar** [comment]
> > Similar to the use of `flaky` in our `.t` tests.
> 
> That's exactly why I'm not of this - If there's a problem, this problem needs to be fixed, not ignored and "hidden" someplace no one will find, or care about.
> 

Ack. But its not the case most of the times. Maybe the TC has to be modified or it is still being debugged. Or maybe there's an open bug on it being worked on. In those scenario's, unless and until it is fixed, I don't feel it might add to value to run it only to see the failure.

> > I think we can use it in cases where we would want to skip 1 or 2 test cases or some test cases related to a particular component due to some bug which may not be corrected immediately and we want to test all other test cases.
> 
> This takes things from another view.
> If a given test was working fine up until now, and due to some recent change (in the product's code) is now failing, what's the point of just ignoring this failure? The whole point is to prevent regression.
> If this test was failing from the start (due to an actual bug in the product), this test shouldn't be merged until the product itself is fixed.
> 
> IMO, the only case when tests needs to be skipped is if the config provided by the user cannot satisfy this particular tests requirements (e.g. the test MUST HAVE 10 servers to operate, but the environment only contains 5).

Let's take a middle ground here. How about we allow skipping of tests but then show the tests which have been skipped ? That might help us keep a tab on test cases with issues that have to be solved.

**Comment by BarakSason** [comment]
The normal workflow (ideally) should be that once a test was merged, it should never be marked to be skipped.
If a test was merged and suddenly fails it can be due to one of the following:

1. The test had some inherent bug was was not detected initially (e.g. some race case) and was detected in larger testing
2. A code change in the products suddenly fails the test - in this case we have actual regression

The ideal way to handle both of these is to fix what's broken.
However, since the situation is not always ideal due to priorities, I can accept, that in certain cases, excluding a test might be necessary, however I disagree with the implementation presented here.
With this implementation, certain TCs will be marked to skipped and will just be forgotten (we see this very well in Gluster).
I suggest to handle this in a different way - Add an "exclude" section to the config file and add there what tests needs to be skipped - This way the information is always in front of the developer's eyes and things have a much lesser change of being forgotten.
Moreover, from a design and OOP perspective, it's not the test's responsibility to tell the framework to ignore it, it should be the other way around - The framework should "know" which tests to exclude.

> Let's take a middle ground here. How about we allow skipping of tests but then show the tests which have been skipped ? That might help us keep a tab on test cases with issues that have to be solved.

Lets differentiate between "skipped" and "excluded":

- Skipped = Was not able to execute due to lacking environment
- Excluded = Was not executed as the user marked this test to be excluded

**Comment by srijan-sivakumar** [comment]
> The normal workflow (ideally) should be that once a test was merged, it should never be marked to be skipped.
> If a test was merged and suddenly fails it can be due to one of the following:
> 
>     1. The test had some inherent bug was was not detected initially (e.g. some race case) and was detected in larger testing
> 
>     2. A code change in the products suddenly fails the test - in this case we have actual regression
> 
> 
> The ideal way to handle both of these is to fix what's broken.
> However, since the situation is not always ideal due to priorities, I can accept, that in certain cases, excluding a test might be necessary, however I disagree with the implementation presented here.
> With this implementation, certain TCs will be marked to skipped and will just be forgotten (we see this very well in Gluster).
> I suggest to handle this in a different way - Add an "exclude" section to the config file and add there what tests needs to be skipped - This way the information is always in front of the developer's eyes and things have a much lesser change of being forgotten.

I feel this is similar to adding skip inside the test case. In the CI nobody would be going in to check the config most of the times. I would rather focus on the result presented after a test run which shows how many tests are skipped. This metrics is what can help in putting the onus on the development team to fix the issues.

> Moreover, from a design and OOP perspective, it's not the test's responsibility to tell the framework to ignore it, it should be the other way around - The framework should "know" which tests to exclude.
> 

I beg to differ in this case. The framework can only judge TCs to be skipped if the framework cannot provide the requisite environment for the TC to run. But if the failure is happening due to the underlying logic of the platform which in our case is glusterfs, then I don't think it is the framework which is responsible, the onus is on the test case.

> > Let's take a middle ground here. How about we allow skipping of tests but then show the tests which have been skipped ? That might help us keep a tab on test cases with issues that have to be solved.
> 
> Lets differentiate between "skipped" and "excluded":
> 
>     * Skipped = Was not able to execute due to lacking environment
> 
>     * Excluded = Was not executed as the user marked this test to be excluded

We can add the above classification but then again I do feel strongly that 
1. Skipped can be handled by framework given the fact that framework has the picture of the environment not the TCs and the decision to skip a test can be done on the go.
2. The Exclusion is not dynamic. But then again, I don't think adding the details in config would make us quicker look into the issue. But its rather the end result which we always take into consideration and the comparison iteratively will push for changes.

**Comment by BarakSason** [comment]
> I feel this is similar to adding skip inside the test case. In the CI nobody would be going in to check the config most of the times. I would rather focus on the result presented after a test run which shows how many tests are skipped. This metrics is what can help in putting the onus on the development team to fix the issues.
> 

In that regard it will absolutely not matter whether a flag will exist in the TC, or the TC will be excluded through the config file - if this test was supposed to run and it's marked, it should appear as "excluded" (not skipped) in the results.

> I beg to differ in this case. The framework can only judge TCs to be skipped if the framework cannot provide the requisite environment for the TC to run. But if the failure is happening due to the underlying logic of the platform which in our case is glusterfs, then I don't think it is the framework which is responsible, the onus is on the test case.
> 

Sorry, not agreeing here.
TC is a set of operations, not more not less. Judgment is not TC responsibility.
If a TC needs to be excluded due to product issue, no change should be done in the TC, it should be marked externally. Why should the TC code (changing a flag is changing code) change?

> We can add the above classification but then again I do feel strongly that
> 
>     1. Skipped can be handled by framework given the fact that framework has the picture of the environment not the TCs and the decision to skip a test can be done on the go.
> 
>     2. The Exclusion is not dynamic. But then again, I don't think adding the details in config would make us quicker look into the issue. But its rather the end result which we always take into consideration and the comparison iteratively will push for changes.

1 - My intention was that skipping tests will be determined at runtime, this should be a framework operation, was that not clear?
2 - IMO the config file approach is preferable for the reasons I've mentioned.

**Review by srijan-sivakumar — CHANGES_REQUESTED** [review]
@nishith-vihar rebase this on the current main and see what changes have been done wrt params handler.

**Pull request merged**
