### PR TITLE
[Tools] Test conversion script.

### PR DESCRIPTION
**Pull request by srijan-sivakumar**
Added a test conversion script ( does minimal set of conversion )
and its indication in the migratingTc.md.

Fixes: #364

Signed-off-by: srijan-sivakumar <ssivakum@redhat.com>

### CODE REVIEW

**Comment by nik-redhat** [comment]
Any usage tips? as a comment or so?

**Comment by srijan-sivakumar** [comment]
> Any usage tips? as a comment or so? :p

Just give a path..of the file which you want to convert..I'm working on the documentation on design thought. Will update it in some time in this patch.

**Comment by srijan-sivakumar** [comment]
@nik-redhat added the docs..

**Review by aujjwal-redhat — APPROVED** [review]
LGTM

**Pull request merged**
