### PR TITLE
Migrated TC test_volume_status_show_bricks_online_though_brickpath_deleted

### PR DESCRIPTION
**Pull request by nik-redhat**
Migrated TC [test_volume_status_show_bricks_online_though_brickpath_deleted](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_volume_status_show_bricks_online_though_brickpath_deleted.py)
Also, added the op `are_bricks_online`

Fixes: #534 
Updates: #292 
Signed-off-by: nik-redhat <nladha@redhat.com>

### CODE REVIEW

**Comment by nik-redhat** [comment]
Test Run:
```
Summary:
+---------------+-------+-------------------+
|    Category   | Cases |    Pass Percent   |
+---------------+-------+-------------------+
| nonDisruptive |   0   |         0         |
|   Disruptive  |   1   | 57.14285714285714 |
|     Total     |   1   | 57.14285714285714 |
+---------------+-------+-------------------+
Table:
 test_volume_status_show_bricks_online_though_brickpath_deleted
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|     dist    |     PASS    | 29.335270643234253 |
|     rep     |     PASS    | 29.787981033325195 |
|     arb     |     PASS    | 29.51219940185547  |
|   dist-rep  |     FAIL    | 26.573692798614502 |
|     disp    |     PASS    | 30.771228075027466 |
|   dist-arb  |     FAIL    | 36.39481782913208  |
|  dist-disp  |     FAIL    | 27.670334100723267 |
+-------------+-------------+--------------------+



Framework runtime : 212.96337509155273
```
The test is expected to fail for dist-rep, dist-arb and dist-disp if we have multiple bricks hosted from the same brick root in a node.
It can fail for dist also since we use the count as 4, but as we do random selection the test passes occasionally.

To have the test pass completely, we need 6 servers at least or 3 or more servers with each having 2 brick roots.

**Comment by srijan-sivakumar** [comment]
> Test Run:
> 
> ```
> Summary:
> +---------------+-------+-------------------+
> |    Category   | Cases |    Pass Percent   |
> +---------------+-------+-------------------+
> | nonDisruptive |   0   |         0         |
> |   Disruptive  |   1   | 57.14285714285714 |
> |     Total     |   1   | 57.14285714285714 |
> +---------------+-------+-------------------+
> Table:
>  test_volume_status_show_bricks_online_though_brickpath_deleted
>  
> +-------------+-------------+--------------------+
> | Volume Type | Test Result |  Time taken (sec)  |
> +-------------+-------------+--------------------+
> |     dist    |     PASS    | 29.335270643234253 |
> |     rep     |     PASS    | 29.787981033325195 |
> |     arb     |     PASS    | 29.51219940185547  |
> |   dist-rep  |     FAIL    | 26.573692798614502 |
> |     disp    |     PASS    | 30.771228075027466 |
> |   dist-arb  |     FAIL    | 36.39481782913208  |
> |  dist-disp  |     FAIL    | 27.670334100723267 |
> +-------------+-------------+--------------------+
> 
> 
> 
> Framework runtime : 212.96337509155273
> ```
> 
> The test is expected to fail for dist-rep, dist-arb and dist-disp if we have multiple bricks hosted from the same brick root in a node.
> It can fail for dist also since we use the count as 4, but as we do random selection the test passes occasionally.
> 
> To have the test pass completely, we need 6 servers at least or 3 or more servers with each having 2 brick roots.

@nik-redhat let's have a check at the beginning of the test on the length of the self.server_list. If it is less than 6, let's fail this test. We can justify this as a requirement for environment.

**Comment by nik-redhat** [comment]
It can work with 3 or more but with 2 brick roots. So, that check won't satisfy that.

**Comment by srijan-sivakumar** [comment]
> It can work with 3 or more but with 2 brick roots. So, that check won't satisfy that.

Cool. we can have two level of checks then. If the count of servers is not 6, then the brick_roots per node should be 2. We do have the brick_root count with us, so I think we can have this validation.

**Comment by nik-redhat** [comment]
> > It can work with 3 or more but with 2 brick roots. So, that check won't satisfy that.
> 
> Cool. we can have two level of checks then. If the count of servers is not 6, then the brick_roots per node should be 2. We do have the brick_root count with us, so I think we can have this validation.

Ack....will update that.

**Comment by nik-redhat** [comment]
@srijan-sivakumar done.

**Review by srijan-sivakumar — APPROVED** [review]
LGTM

**Pull request merged**
