### PR TITLE
Removed redant from filenames

### PR DESCRIPTION
**Pull request by aujjwal-redhat**
redant_test_runner renamed to test_runner
redant_test_main renamed to gluster_test_main

Fixes: #114

Signed-off-by: aujjwal-redhat <aujjwal@redhat.com>

### CODE REVIEW

**Comment by srijan-sivakumar** [comment]
@aujjwal-redhat , any particular reason as to the renaming ? Any functional effect ?

**Comment by aujjwal-redhat** [comment]
> @aujjwal-redhat , any particular reason as to the renaming ? Any functional effect ?

Barak has told to not use redant in file name.

**Comment by nishith-vihar** [comment]
> > @aujjwal-redhat , any particular reason as to the renaming ? Any functional effect ?
> 
> Barak has told to not use redant in file name.

I thought he mentioned that only in case of parsing

**Comment by aujjwal-redhat** [comment]
> > > @aujjwal-redhat , any particular reason as to the renaming ? Any functional effect ?
> > 
> > 
> > Barak has told to not use redant in file name.
> 
> I thought he mentioned that only in case of parsing

Oh ok. Then I guess we can ignore this patch.

**Comment by aujjwal-redhat** [comment]
Closing this patch as it is not related to the asked changes.

**Pull request closed without merging**
