### PR TITLE
Added the summary stats in results

### PR DESCRIPTION
**Pull request by aujjwal-redhat**
Added the summary stats in result_handler component.

Fixes: #417

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

### CODE REVIEW

**Comment by aujjwal-redhat** [comment]
Screenshot from 2021-05-24 14-18-36

**Comment by aujjwal-redhat** [comment]
Ran it on the complete suite:
functional tests: 21
example : 4

**Comment by srijan-sivakumar** [comment]
@aujjwal-redhat this new summary will come at the bottom of the spreadsheet right ?

**Comment by aujjwal-redhat** [comment]
> @aujjwal-redhat this new summary will come at the bottom of the spreadsheet right ?

yeah

**Comment by srijan-sivakumar** [comment]
> > @aujjwal-redhat this new summary will come at the bottom of the spreadsheet right ?
> 
> yeah

Can it be shifted to the top of the sheet instead because people looking at the spreadsheet would like the summary to be at the top so that they can just glance at it and learn of the overall results rather than scrolling till the bottom. Imagine a scenario with 400 test cases as to how much scrolling would required for getting the results.

**Comment by aujjwal-redhat** [comment]
> > > @aujjwal-redhat this new summary will come at the bottom of the spreadsheet right ?
> > 
> > 
> > yeah
> 
> Can it be shifted to the top of the sheet instead because people looking at the spreadsheet would like the summary to be at the top so that they can just glance at it and learn of the overall results rather than scrolling till the bottom. Imagine a scenario with 400 test cases as to how much scrolling would required for getting the results.

ok

**Comment by aujjwal-redhat** [comment]
@srijan-sivakumar pushed the table to top

**Comment by aujjwal-redhat** [comment]
```bash
Summary:
+---------------+-------+------------------+
|    Category   | Cases |   Pass Percent   |
+---------------+-------+------------------+
| nonDisruptive |   4   | 92.3076923076923 |
|   Disruptive  |   0   |        0         |
|     Total     |   4   | 92.3076923076923 |
+---------------+-------+------------------+
Table:
 vol_create_test
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|     dist    |     PASS    | 21.835272789001465 |
.
.
.
```

**Review by srijan-sivakumar — APPROVED** [review]
LGTM

**Pull request merged**
