### PR TITLE
Updated the negative case handling in few of the TCs

### PR DESCRIPTION
**Pull request by nik-redhat**
Fix:
Updated the TCs to use the `excep` flag to check for negative scenarios
and raise an exception only if the outcome is not as expected

Fixes: #638

Signed-off-by: nik-redhat <nladha@redhat.com>

### CODE REVIEW

**Review by aujjwal-redhat — DISMISSED** [review]
LGTM. 
SS for the modified tests @nik-redhat

**Comment by nik-redhat** [comment]
> LGTM.
> SS for the modified tests @nik-redhat

Yes, I am testing those. There are few issues actually, so I will add the test run after committing those.

**Comment by aujjwal-redhat** [comment]
> Yes, I am testing those. There are few issues actually, so I will add the test run after committing those.

Ack

**Comment by nik-redhat** [comment]
Test run:
```
Table:
 test_add_brick_when_quorum_not_met
 
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time taken (HH:MM:SS) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     dist    |     PASS    |        00:04:11       |     N/A     |
+-------------+-------------+-----------------------+-------------+

Framework runtime : 00 hours 04 minutes 23 seconds
```
```
Table:
 test_profile_start_with_quorum_not_met
 
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time taken (HH:MM:SS) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     dist    |     PASS    |        00:00:36       |     N/A     |
|     rep     |     PASS    |        00:00:45       |     N/A     |
|     disp    |     PASS    |        00:00:45       |     N/A     |
|   dist-rep  |     PASS    |        00:00:54       |     N/A     |
|  dist-disp  |     PASS    |        00:00:52       |     N/A     |
+-------------+-------------+-----------------------+-------------+

Framework runtime : 00 hours 04 minutes 04 seconds
```
```
Table:
 test_volume_status_xml
 
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time taken (HH:MM:SS) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|   Generic   |     PASS    |        00:00:21       |     N/A     |
+-------------+-------------+-----------------------+-------------+

Framework runtime : 00 hours 00 minutes 34 seconds
```
```
Table:
 test_validate_auth_allow_and_auth_reject
 
+-------------+-------------+-----------------------+-------------+
| Volume Type | Test Result | Time taken (HH:MM:SS) | Skip Reason |
+-------------+-------------+-----------------------+-------------+
|     rep     |     PASS    |        00:00:37       |     N/A     |
|     dist    |     PASS    |        00:00:40       |     N/A     |
|   dist-rep  |     PASS    |        00:00:52       |     N/A     |
|  dist-disp  |     PASS    |        00:00:53       |     N/A     |
|     arb     |     PASS    |        00:00:41       |     N/A     |
|   dist-arb  |     PASS    |        00:00:54       |     N/A     |
+-------------+-------------+-----------------------+-------------+

Framework runtime : 00 hours 04 minutes 50 seconds
```

**Comment by nik-redhat** [comment]
My VMs don't support testing of the TC `test_reserved_port_range_for_gluster` :p

**Review by aujjwal-redhat — APPROVED** [review]

**Pull request merged**
