### PR TITLE
Volume Mount operation is shifted to VolumeOps

### PR DESCRIPTION
**Pull request by nishith-vihar**
The volume mount operation is shifted from io_ops to
VolumeOps library

Fixes: #73
Signed-off-by: Nishith Vihar Sakinala <nsakinal@redhat.com>

### CODE REVIEW

**Comment by nik-redhat** [comment]
Why?

**Comment by nishith-vihar** [comment]
> Why?

Actually barak has told that volume mount should come in volumeOps library

**Comment by nik-redhat** [comment]
> > Why?
> 
> Actually barak has told that volume mount should come in volumeOps library

Okay

**Comment by nik-redhat** [comment]
Can you do one thing, for now, change the name of `Redant` to `redant_test` for the time being to fix the flake issue.

**Review by nik-redhat — APPROVED** [review]

**Pull request merged**
