### PR TITLE
Migrated TC test_peer_probe_firewall_ports_not_opened

### PR DESCRIPTION
**Pull request by nik-redhat**
Migrated TC [test_peer_probe_firewall_ports_not_opened](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_peer_probe_firewall_ports_not_opened.py)

Fixes: #429 
Updates: #292 
Signed-off-by: nik-redhat <nladha@redhat.com>

### CODE REVIEW

**Comment by nik-redhat** [comment]
This test is only applicable if we hace the setup done with firewall enabled and using rpm installation, because in case of rpm installation we get the firewall service files for glusterfs and rpm, is what I understand.

**Comment by srijan-sivakumar** [comment]
> This test is only applicable if we hace the setup done with firewall enabled and using rpm installation, because in case of rpm installation we get the firewall service files for glusterfs and rpm, is what I understand.

The CI does have rpm installed env.

**Comment by nik-redhat** [comment]
Ok, but is the peering done with firewall enabled? I don't think so..

**Comment by srijan-sivakumar** [comment]
> Ok, but is the peering done with firewall enabled? I don't think so...

No..we still have to test that. I'm thinking of doing the testings post 9th...

**Comment by nik-redhat** [comment]
Cool, marked under excluded, for the time being, we are good with this PR.

**Review by srijan-sivakumar — APPROVED** [review]

**Pull request merged**
