### PR TITLE
[Test] Migration of a brick test.

### PR DESCRIPTION
**Pull request by srijan-sivakumar**
Migration of -
`test_brick_status_when_quorum_not_met`
    
Fixes: #357
    
Signed-off-by: srijan-sivakumar <ssivakum@redhat.com>

### CODE REVIEW

**Review by nik-redhat — COMMENTED** [review]
I think we can have a terminate function for this as well? Or considering we are doing it in the parent_terminate we can choose to bypass it?

**Comment by srijan-sivakumar** [comment]
> I think we can have a terminate function for this as well? Or considering we are doing it in the parent_terminate we can choose to bypass it?

Yeah..let's not duplicate the checks in parent terminate...

**Review by nik-redhat — APPROVED** [review]

**Comment by nik-redhat** [comment]
Btw test output? :p

**Comment by srijan-sivakumar** [comment]
Ahh..wait. I forgot to add that. Let me re-run and attach :p

**Comment by srijan-sivakumar** [comment]
```
(redant-demo) [root@rhsdev-virt05 redant]# python3 core/redant_main.py -c ../rconfig.yml -t tests/functional/glusterd/test_brick_status_when_quorum_not_met.py -ll D -sp
test_brick_status_when_quorum_not_met-dist-rep PASS

Summary:
+---------------+-------+--------------+
|    Category   | Cases | Pass Percent |
+---------------+-------+--------------+
| nonDisruptive |   0   |      0       |
|   Disruptive  |   1   |    100.0     |
|     Total     |   1   |    100.0     |
+---------------+-------+--------------+
Table:
 test_brick_status_when_quorum_not_met
 
+-------------+-------------+------------------+
| Volume Type | Test Result | Time taken (sec) |
+-------------+-------------+------------------+
|   dist-rep  |     PASS    | 66.2678894996643 |
+-------------+-------------+------------------+



Framework runtime : 70.25544905662537
```

**Pull request merged**
