### PR TITLE
Fixed linting issues of io_ops

### PR DESCRIPTION
**Pull request by aujjwal-redhat**
Fixed lint and flake issues of io_ops
Updates: #58

Signed-off-by: aujjwal-redhat <aujjwal@redhat.com>

### CODE REVIEW

**Comment by nik-redhat** [comment]
@aujjwal-redhat could you please resolve the conflicts, by doing a rebase?

**Comment by aujjwal-redhat** [comment]
@nik-redhat yeah sure

**Comment by aujjwal-redhat** [comment]
@nik-redhat is it ok now?

**Comment by aujjwal-redhat** [comment]
@neesingh-rh will be submitting a different patch with final changes and linting. To prevent another conflict I am closing this PR.

@nik-redhat

**Pull request closed without merging**
