### PR TITLE
Result of test cases handling

### PR DESCRIPTION
**Pull request by aujjwal-redhat**
Added result handler. Displaying the test stats for both disruptive and non-disruptive.

Fixes: #136

Current table status:
Screenshot from 2021-03-26 11-59-47

### CODE REVIEW

**Comment by aujjwal-redhat** [comment]
Getting the table in this form:


```js
Table:
test_peer_probe_detach
+-------------+-------------+------------+
| Volume Type | Test Result | Time taken |
+-------------+-------------+------------+
|     dist    |     PASS    |     0      |
|     rep     |     PASS    |     0      |
|     arb     |     PASS    |     0      |
|     disp    |     PASS    |     0      |
|   dist-rep  |     PASS    |     0      |
|   dist-arb  |     PASS    |     0      |
+-------------+-------------+------------+
test_volume_create_delete
+-------------+-------------+------------+
| Volume Type | Test Result | Time taken |
+-------------+-------------+------------+
|     dist    |     PASS    |     0      |
|     rep     |     PASS    |     0      |
|     arb     |     PASS    |     0      |
|     disp    |     PASS    |     0      |
+-------------+-------------+------------+
test_glusterd_start_stop
+-------------+-------------+---------------------+
| Volume Type | Test Result |      Time taken     |
+-------------+-------------+---------------------+
|     dist    |     PASS    | 0.45673370361328125 |
|     rep     |     PASS    |  0.466259241104126  |
|     arb     |     PASS    |  0.4558906555175781 |
|     disp    |     PASS    |  0.4487576484680176 |
+-------------+-------------+---------------------+
(redantenv) [root@serverc redant]# git status
```

**Comment by aujjwal-redhat** [comment]
Non-concurrent test is working. Tested it by making test_glusterd_start_stop disruptive and just passing the run_test( that's why time is quite less).

Concurrent: Non-disruptive tests yet to be covered.

**Comment by aujjwal-redhat** [comment]
Tested for both non-concurrent and concurrent:
For disruptive converted test_glusterd_start_stop from non-disruptive to disruptive and tested locally.
Screenshot from 2021-03-26 11-17-44

**Comment by aujjwal-redhat** [comment]
Tested for both non-concurrent and concurrent:
For testing disruptive tests, converted test_glusterd_start_stop from non-disruptive to disruptive and tested locally. It was working.

**Comment by srijan-sivakumar** [comment]
@aujjwal-redhat , rebase and push the changes again. The directory structure has been modified.

**Comment by aujjwal-redhat** [comment]
@srijan-sivakumar I have made the changes and tested the code as well.
# Screenshots

Screenshot from 2021-03-29 09-39-33-1


Some tests failed because peer was not in cluster. So it verifies the fail message as well.
The result table also shows the status of the tests perfectly.

Screenshot from 2021-03-29 09-39-48

## Logs

Screenshot from 2021-03-29 09-40-21

### As we can see the logs are also showing the error that occurred.

Screenshot from 2021-03-29 09-42-21

**Comment by srijan-sivakumar** [comment]
Can we also get an output wrt how much time it took for the suite to run, i.e. the framework runtime before these tables.

**Comment by srijan-sivakumar** [comment]
Also couple of points...
1. Result handler should be inside core. 
2. Make it flag controlled inside so that the invoker can either take it in a file or output it to the stdout.

**Review by srijan-sivakumar — APPROVED** [review]
LGTM

**Pull request merged**
