### PR TITLE
ret_msg value is updated

### PR DESCRIPTION
**Pull request by nishith-vihar**
ret_msg is updated with new value from the latest command execution.

Fixes: #468
Signed-off-by: Nishith Vihar Sakinala <nsakinal@redhat.com>

### CODE REVIEW

**Review by aujjwal-redhat — APPROVED** [review]
LGTM

**Comment by srijan-sivakumar** [comment]
@nishith-vihar just one nit: can you modify the PR header and add some description. Simple bug fix won't be helpful for reviewers as well as for people in future looking at the fix.

**Comment by nishith-vihar** [comment]
> @nishith-vihar just one nit: can you modify the PR header and add some description. Simple bug fix won't be helpful for reviewers as well as for people in future looking at the fix.

Modified it

**Comment by srijan-sivakumar** [comment]
LGTM, but let's wait before merging this. I'll run it in the env wherein I have the rpms.

**Review by srijan-sivakumar — APPROVED** [review]

**Pull request merged**
