### PR TITLE
Added test_change_reserve_limit_to_wrong_values 

### PR DESCRIPTION
**Pull request by aujjwal-redhat**
Migrated the test case from the glusto tests and added it in the redant
tests folder. Modified the test as per the redant standards and set of
functionalities.

Updates : #292
Fixes : #297

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

### CODE REVIEW

**Comment by srijan-sivakumar** [comment]
@aujjwal-redhat , in the try, we have a for loop looping over three values, the very first value will throw an error and we'll exit this try-catch blog after logging it, what about the other two values in the loop which we never tried ?

**Comment by aujjwal-redhat** [comment]
> @aujjwal-redhat , in the try, we have a for loop looping over three values, the very first value will throw an error and we'll exit this try-catch blog after logging it, what about the other two values in the loop which we never tried ?

Ack. We need to have atry catch inside the for loop.

**Comment by srijan-sivakumar** [comment]
The approach taken is good, this is how we need to test the negative scenarios..with a try-catch block, but the block should be around the function which is expected to fail...so the code should have been

```
            for char_type in (string.ascii_letters, string.punctuation,
                              string.printable):

                temp_val = self.get_random_string(char_type)
                temp_val = temp_val.replace("'", "").replace("&", "")
                value = "'{}'".format(temp_val)
                try:
                    redant.set_volume_options(self.vol_name, {key: value},
                                              self.server_list[0])
                except Exception:
                    redant.logger.info("Wrong value was tested successfully")
```

**Comment by srijan-sivakumar** [comment]
> > @aujjwal-redhat , in the try, we have a for loop looping over three values, the very first value will throw an error and we'll exit this try-catch blog after logging it, what about the other two values in the loop which we never tried ?
> 
> Ack. We need to have atry catch inside the for loop.

Yes..do check my previous comment. It solves this conundrum. Now we need to see how to have a mechanism to prevent this type of try-except being added directly, we can have a function which takes in the function to execute, params and with that the message to be displayed. Though we can take this up later in a different patch,

**Comment by aujjwal-redhat** [comment]
@srijan-sivakumar now all the values are taken care of
```bash
[2021-05-11 14:39:12,015] INFO  - Running gluster volume set test_change_reserve_limit_to_wrong_values-dist-rep storage.reserve 'fThY' --mode=script --xml on 10.70.43.74
[2021-05-11 14:39:12,302] DEBUG  - {'msg': {'opRet': '-1', 'opErrno': '30800', 'opErrstr': 'invalid number format "fThY" in "option reserve"', 'cliOp': 'volSet', 'output': 'Set volume unsuccessful'}, 'Flag': True, 'node': '10.70.43.74', 'cmd': "gluster volume set test_change_reserve_limit_to_wrong_values-dist-rep storage.reserve 'fThY' --mode=script --xml", 'error_code': 0}
[2021-05-11 14:39:12,303] ERROR  - invalid number format "fThY" in "option reserve"
[2021-05-11 14:39:12,303] INFO  - Wrong value was tested successfully
[2021-05-11 14:39:12,304] INFO  - Running gluster volume set test_change_reserve_limit_to_wrong_values-dist-rep storage.reserve '.;#|' --mode=script --xml on 10.70.43.74
[2021-05-11 14:39:12,537] DEBUG  - {'msg': {'opRet': '-1', 'opErrno': '30800', 'opErrstr': 'invalid number format ".;#|" in "option reserve"', 'cliOp': 'volSet', 'output': 'Set volume unsuccessful'}, 'Flag': True, 'node': '10.70.43.74', 'cmd': "gluster volume set test_change_reserve_limit_to_wrong_values-dist-rep storage.reserve '.;#|' --mode=script --xml", 'error_code': 0}
[2021-05-11 14:39:12,538] ERROR  - invalid number format ".;#|" in "option reserve"
[2021-05-11 14:39:12,538] INFO  - Wrong value was tested successfully
[2021-05-11 14:39:12,538] INFO  - Running gluster volume set test_change_reserve_limit_to_wrong_values-dist-rep storage.reserve '1,JL' --mode=script --xml on 10.70.43.74
[2021-05-11 14:39:12,794] DEBUG  - {'msg': {'opRet': '-1', 'opErrno': '30800', 'opErrstr': 'invalid number format "1,JL" in "option reserve"', 'cliOp': 'volSet', 'output': 'Set volume unsuccessful'}, 'Flag': True, 'node': '10.70.43.74', 'cmd': "gluster volume set test_change_reserve_limit_to_wrong_values-dist-rep storage.reserve '1,JL' --mode=script --xml", 'error_code': 0}
[2021-05-11 14:39:12,795] ERROR  - invalid number format "1,JL" in "option reserve"
[2021-05-11 14:39:12,795] INFO  - Wrong value was tested successfully
[2021-05-11 14:39:12,796] INFO  - Running gluster volume set test_change_reserve_limit_to_wrong_values-dist-rep storage.reserve -1% --mode=script --xml on 10.70.43.74
[2021-05-11 14:39:12,885] DEBUG  - {'msg': {'opRet': '-1', 'opErrno': '30800', 'opErrstr': 'invalid number format "-1%" in "option reserve"', 'cliOp': 'volSet', 'output': 'Set volume unsuccessful'}, 'Flag': True, 'node': '10.70.43.74', 'cmd': 'gluster volume set test_change_reserve_limit_to_wrong_values-dist-rep storage.reserve -1% --mode=script --xml', 'error_code': 0}
[2021-05-11 14:39:12,885] ERROR  - invalid number format "-1%" in "option reserve"
[2021-05-11 14:39:12,885] INFO  - Wrong value was tested successfully
[2021-05-11 14:39:12,885] INFO  - Running gluster volume set test_change_reserve_limit_to_wrong_values-dist-rep storage.reserve -101% --mode=script --xml on 10.70.43.74
[2021-05-11 14:39:13,053] DEBUG  - {'msg': {'opRet': '-1', 'opErrno': '30800', 'opErrstr': 'invalid number format "-101%" in "option reserve"', 'cliOp': 'volSet', 'output': 'Set volume unsuccessful'}, 'Flag': True, 'node': '10.70.43.74', 'cmd': 'gluster volume set test_change_reserve_limit_to_wrong_values-dist-rep storage.reserve -101% --mode=script --xml', 'error_code': 0}
[2021-05-11 14:39:13,053] ERROR  - invalid number format "-101%" in "option reserve"
[2021-05-11 14:39:13,053] INFO  - Wrong value was tested successfully
[2021-05-11 14:39:13,053] INFO  - Running gluster volume set test_change_reserve_limit_to_wrong_values-dist-rep storage.reserve 101% --mode=script --xml on 10.70.43.74
[2021-05-11 14:39:13,156] DEBUG  - {'msg': {'opRet': '-1', 'opErrno': '30800', 'opErrstr': "'101.000000' in 'option reserve 101%' is out of range [0 - 100]", 'cliOp': 'volSet', 'output': 'Set volume unsuccessful'}, 'Flag': True, 'node': '10.70.43.74', 'cmd': 'gluster volume set test_change_reserve_limit_to_wrong_values-dist-rep storage.reserve 101% --mode=script --xml', 'error_code': 0}
[2021-05-11 14:39:13,156] ERROR  - '101.000000' in 'option reserve 101%' is out of range [0 - 100]
[2021-05-11 14:39:13,156] INFO  - Wrong value was tested successfully
[2021-05-11 14:39:13,156] INFO  - Running gluster volume set test_change_reserve_limit_to_wrong_values-dist-rep storage.reserve -1 --mode=script --xml on 10.70.43.74
[2021-05-11 14:39:13,301] DEBUG  - {'msg': {'opRet': '-1', 'opErrno': '30800', 'opErrstr': 'invalid number format "-1" in "option reserve"', 'cliOp': 'volSet', 'output': 'Set volume unsuccessful'}, 'Flag': True, 'node': '10.70.43.74', 'cmd': 'gluster volume set test_change_reserve_limit_to_wrong_values-dist-rep storage.reserve -1 --mode=script --xml', 'error_code': 0}
[2021-05-11 14:39:13,301] ERROR  - invalid number format "-1" in "option reserve"
[2021-05-11 14:39:13,301] INFO  - Wrong value was tested successfully
[2021-05-11 14:39:13,301] INFO  - Running gluster volume set test_change_reserve_limit_to_wrong_values-dist-rep storage.reserve -101 --mode=script --xml on 10.70.43.74
[2021-05-11 14:39:13,429] DEBUG  - {'msg': {'opRet': '-1', 'opErrno': '30800', 'opErrstr': 'invalid number format "-101" in "option reserve"', 'cliOp': 'volSet', 'output': 'Set volume unsuccessful'}, 'Flag': True, 'node': '10.70.43.74', 'cmd': 'gluster volume set test_change_reserve_limit_to_wrong_values-dist-rep storage.reserve -101 --mode=script --xml', 'error_code': 0}
[2021-05-11 14:39:13,429] ERROR  - invalid number format "-101" in "option reserve"
[2021-05-11 14:39:13,429] INFO  - Wrong value was tested successfully
```

**Pull request merged**
