### PR TITLE
Halo and hard terminate introduction

### PR DESCRIPTION
**Pull request by srijan-sivakumar**
Fixes: #593
Signed-off-by: srijan-sivakumar <ssivakum@redhat.com>

### CODE REVIEW

**Comment by srijan-sivakumar** [comment]
During the run

```
(redant-demo) [root@rhsdev-virt05 redant]# python3 core/redant_main.py -c ../rconfig.yml -t tests/functional/glusterd/test_readonly_option_on_volume.py -ll D -sp
✔ Param Handling Success.
✔ Test List built
✔ Log dir creation successful.
⠧ Setting up environment
```

After run

```
(redant-demo) [root@rhsdev-virt05 redant]# python3 core/redant_main.py -c ../rconfig.yml -t tests/functional/glusterd/test_readonly_option_on_volume.py -ll D -sp
✔ Param Handling Success.
✔ Test List built
✔ Log dir creation successful.
✔ Environment setup successful.
✔ vol_create_test-dist Succeeded
✔ vol_create_test-rep Succeeded
✔ test_readonly_option_on_volume-dist Succeeded
✔ test_readonly_option_on_volume-rep Succeeded
✔ vol_destroy_test-dist Succeeded
✔ vol_destroy_test-rep Succeeded
✔ vol_create_test-dist-rep Succeeded
✔ vol_create_test-disp Succeeded
✔ test_readonly_option_on_volume-disp Succeeded
✔ test_readonly_option_on_volume-dist-rep Succeeded
⠏ Running test case : vol_destroy_test-dist-rep✔ vol_destroy_test-disp Succeeded
✔ vol_destroy_test-dist-rep Succeeded
✔ vol_create_test-dist-disp Succeeded
✔ test_readonly_option_on_volume-dist-disp Succeeded
✔ vol_destroy_test-dist-disp Succeeded
Summary:
+---------------+-------+--------------+
|    Category   | Cases | Pass Percent |
+---------------+-------+--------------+
| nonDisruptive |   1   |    100.0     |
|   Disruptive  |   0   |      0       |
|     Total     |   1   |    100.0     |
+---------------+-------+--------------+
Table:
 vol_create_test
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|     dist    |     PASS    |  10.8029146194458  |
|     rep     |     PASS    | 11.13418197631836  |
|   dist-rep  |     PASS    | 11.637465000152588 |
|     disp    |     PASS    | 14.221710443496704 |
|  dist-disp  |     PASS    | 10.73568058013916  |
+-------------+-------------+--------------------+

 test_readonly_option_on_volume
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|     dist    |     PASS    | 19.350616931915283 |
|     rep     |     PASS    | 20.263810873031616 |
|     disp    |     PASS    | 21.186453580856323 |
|   dist-rep  |     PASS    | 22.83795928955078  |
|  dist-disp  |     PASS    | 19.040451288223267 |
+-------------+-------------+--------------------+

 vol_destroy_test
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|     dist    |     PASS    | 12.533827066421509 |
|     rep     |     PASS    | 13.885347127914429 |
|     disp    |     PASS    | 13.526879787445068 |
|   dist-rep  |     PASS    | 15.284170866012573 |
|  dist-disp  |     PASS    | 9.803711652755737  |
+-------------+-------------+--------------------+



Framework runtime : 143.61520552635193

✔ Tearing down successful.
```

**Comment by srijan-sivakumar** [comment]
The hard terminate will be present before and after the test runs. Coming to the spinners, during the non-disruptive tests, the tasks will be displayed one over the another but atleast gives a picture of something running. Once a process has finished, based on the status, either a cross will be displayed or a tick.

**Comment by srijan-sivakumar** [comment]
```
(redant-demo) [root@rhsdev-virt05 redant]# python3 core/redant_main.py -c ../rconfig.yml -t tests/functional/glusterd/test_readonly_option_on_volume.py -ll D -sp
✔ Param Handling Success.
✔ Test List built
✔ Log dir creation successful.
✔ Environment setup successful.
✔ Running test case : vol_create_test-rep
✔ Running test case : vol_create_test-dist
✔ vol_create_test-dist Succeeded
✔ Running test case : test_readonly_option_on_volume-dist
✔ vol_create_test-rep Succeeded
✔ Running test case : test_readonly_option_on_volume-rep
✔ test_readonly_option_on_volume-dist Succeeded
✔ Running test case : vol_destroy_test-dist
✔ test_readonly_option_on_volume-rep Succeeded
✔ Running test case : vol_destroy_test-rep
✔ vol_destroy_test-dist Succeeded
✔ Running test case : vol_create_test-disp
✔ vol_destroy_test-rep Succeeded
✔ Running test case : vol_create_test-dist-rep
✔ vol_create_test-disp Succeeded
✔ Running test case : test_readonly_option_on_volume-disp
✔ vol_create_test-dist-rep Succeeded
✔ Running test case : test_readonly_option_on_volume-dist-rep
✔ test_readonly_option_on_volume-disp Succeeded
✔ Running test case : vol_destroy_test-disp
✔ test_readonly_option_on_volume-dist-rep Succeeded
✔ Running test case : vol_destroy_test-dist-rep
✔ vol_destroy_test-disp Succeeded
✔ Running test case : vol_create_test-dist-disp
✔ vol_destroy_test-dist-rep Succeeded
✔ vol_create_test-dist-disp Succeeded
✔ Running test case : test_readonly_option_on_volume-dist-disp
✔ test_readonly_option_on_volume-dist-disp Succeeded
✔ Running test case : vol_destroy_test-dist-disp
✔ vol_destroy_test-dist-disp Succeeded
Summary:
+---------------+-------+--------------+
|    Category   | Cases | Pass Percent |
+---------------+-------+--------------+
| nonDisruptive |   1   |    100.0     |
|   Disruptive  |   0   |      0       |
|     Total     |   1   |    100.0     |
+---------------+-------+--------------+
Table:
 vol_create_test
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|     dist    |     PASS    | 9.695330142974854  |
|     rep     |     PASS    | 10.02422308921814  |
|     disp    |     PASS    | 16.002907752990723 |
|   dist-rep  |     PASS    | 13.13490629196167  |
|  dist-disp  |     PASS    | 12.318161487579346 |
+-------------+-------------+--------------------+

 test_readonly_option_on_volume
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|     dist    |     PASS    | 20.232544898986816 |
|     rep     |     PASS    | 21.138492584228516 |
|     disp    |     PASS    | 19.773518323898315 |
|   dist-rep  |     PASS    | 22.45026659965515  |
|  dist-disp  |     PASS    | 20.31755304336548  |
+-------------+-------------+--------------------+

 vol_destroy_test
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|     dist    |     PASS    | 12.925403118133545 |
|     rep     |     PASS    | 14.624824523925781 |
|     disp    |     PASS    | 15.182082414627075 |
|   dist-rep  |     PASS    | 15.921188354492188 |
|  dist-disp  |     PASS    | 10.408336162567139 |
+-------------+-------------+--------------------+



Framework runtime : 148.63183569908142

✔ Tearing down successful.
```

**Comment by srijan-sivakumar** [comment]
> ```
> (redant-demo) [root@rhsdev-virt05 redant]# python3 core/redant_main.py -c ../rconfig.yml -t tests/functional/glusterd/test_readonly_option_on_volume.py -ll D -sp
> ✔ Param Handling Success.
> ✔ Test List built
> ✔ Log dir creation successful.
> ✔ Environment setup successful.
> ✔ Running test case : vol_create_test-rep
> ✔ Running test case : vol_create_test-dist
> ✔ vol_create_test-dist Succeeded
> ✔ Running test case : test_readonly_option_on_volume-dist
> ✔ vol_create_test-rep Succeeded
> ✔ Running test case : test_readonly_option_on_volume-rep
> ✔ test_readonly_option_on_volume-dist Succeeded
> ✔ Running test case : vol_destroy_test-dist
> ✔ test_readonly_option_on_volume-rep Succeeded
> ✔ Running test case : vol_destroy_test-rep
> ✔ vol_destroy_test-dist Succeeded
> ✔ Running test case : vol_create_test-disp
> ✔ vol_destroy_test-rep Succeeded
> ✔ Running test case : vol_create_test-dist-rep
> ✔ vol_create_test-disp Succeeded
> ✔ Running test case : test_readonly_option_on_volume-disp
> ✔ vol_create_test-dist-rep Succeeded
> ✔ Running test case : test_readonly_option_on_volume-dist-rep
> ✔ test_readonly_option_on_volume-disp Succeeded
> ✔ Running test case : vol_destroy_test-disp
> ✔ test_readonly_option_on_volume-dist-rep Succeeded
> ✔ Running test case : vol_destroy_test-dist-rep
> ✔ vol_destroy_test-disp Succeeded
> ✔ Running test case : vol_create_test-dist-disp
> ✔ vol_destroy_test-dist-rep Succeeded
> ✔ vol_create_test-dist-disp Succeeded
> ✔ Running test case : test_readonly_option_on_volume-dist-disp
> ✔ test_readonly_option_on_volume-dist-disp Succeeded
> ✔ Running test case : vol_destroy_test-dist-disp
> ✔ vol_destroy_test-dist-disp Succeeded
> Summary:
> +---------------+-------+--------------+
> |    Category   | Cases | Pass Percent |
> +---------------+-------+--------------+
> | nonDisruptive |   1   |    100.0     |
> |   Disruptive  |   0   |      0       |
> |     Total     |   1   |    100.0     |
> +---------------+-------+--------------+
> Table:
>  vol_create_test
>  
> +-------------+-------------+--------------------+
> | Volume Type | Test Result |  Time taken (sec)  |
> +-------------+-------------+--------------------+
> |     dist    |     PASS    | 9.695330142974854  |
> |     rep     |     PASS    | 10.02422308921814  |
> |     disp    |     PASS    | 16.002907752990723 |
> |   dist-rep  |     PASS    | 13.13490629196167  |
> |  dist-disp  |     PASS    | 12.318161487579346 |
> +-------------+-------------+--------------------+
> 
>  test_readonly_option_on_volume
>  
> +-------------+-------------+--------------------+
> | Volume Type | Test Result |  Time taken (sec)  |
> +-------------+-------------+--------------------+
> |     dist    |     PASS    | 20.232544898986816 |
> |     rep     |     PASS    | 21.138492584228516 |
> |     disp    |     PASS    | 19.773518323898315 |
> |   dist-rep  |     PASS    | 22.45026659965515  |
> |  dist-disp  |     PASS    | 20.31755304336548  |
> +-------------+-------------+--------------------+
> 
>  vol_destroy_test
>  
> +-------------+-------------+--------------------+
> | Volume Type | Test Result |  Time taken (sec)  |
> +-------------+-------------+--------------------+
> |     dist    |     PASS    | 12.925403118133545 |
> |     rep     |     PASS    | 14.624824523925781 |
> |     disp    |     PASS    | 15.182082414627075 |
> |   dist-rep  |     PASS    | 15.921188354492188 |
> |  dist-disp  |     PASS    | 10.408336162567139 |
> +-------------+-------------+--------------------+
> 
> 
> 
> Framework runtime : 148.63183569908142
> 
> ✔ Tearing down successful.
> ```

Latest changes to prevent clunky output.

**Comment by srijan-sivakumar** [comment]
ok...these are just some small high visual changes (except ofcourse the hard terminate )

```
(v1) [root@f05-h06-000-1029p redant]# python3 core/redant_main.py --help
    ____  __________  ___    _   ________
   / __ \/ ____/ __ \/   |  / | / /_  __/
  / /_/ / __/ / / / / /| | /  |/ / / /   
 / _, _/ /___/ /_/ / ___ |/ /|  / / /    
/_/ |_/_____/_____/_/  |_/_/ |_/ /_/     
                                         

usage: redant_main.py [-h] -c CONFIG_FILE -t TEST_DIR [-sp] [-l LOG_DIR]
                      [-ll LOG_LEVEL] [-cc CONCUR_COUNT] [-rf RESULT_PATH]
                      [-xls EXCEL_SHEET]

Redant test framework main script.

optional arguments:
  -h, --help            show this help message and exit
  -c CONFIG_FILE, --config CONFIG_FILE
                        Config file(s) to read.
  -t TEST_DIR, --test-dir TEST_DIR
                        The test directory where TC(s) exist
  -sp, --specific-test-path
                        Path of the specific test to be run from tests/
  -l LOG_DIR, --log-dir LOG_DIR
                        The directory wherein log will be stored.
  -ll LOG_LEVEL, --log-level LOG_LEVEL
                        The log level. Default log level is Info
  -cc CONCUR_COUNT, --concurrency-count CONCUR_COUNT
                        Number of concurrent test runs. Default is 2.
  -rf RESULT_PATH, --result-file RESULT_PATH
                        Result file. Default value is None
  -xls EXCEL_SHEET, --excel-sheet EXCEL_SHEET
                        Spreadsheet for result. Default value is NULL
```

**Review by nishith-vihar — APPROVED** [review]
LGTM

**Pull request merged**
