### PR TITLE
[Core][Common][Test] Sanitize and cleanup

### PR DESCRIPTION
**Pull request by srijan-sivakumar**
Sanitize and cleanup functionalities added.
1. The volume sanitize is used for prepping a volume for the next TC or even to be used within a test case.
2. The volume cleanup is to be used for complete cleanup of volume and its mount.

Also added is the brick dir deletion which is handled at
1. nd_parent_test
2. d_parent_test
3. vol_destroy_test

Fixes: #408
    
Signed-off-by: srijan-sivakumar <ssivakum@redhat.com>

### CODE REVIEW

**Comment by srijan-sivakumar** [comment]
@nik-redhat @nishith-vihar @neesingh-rh @aujjwal-redhat this is ready for review now.

**Review by aujjwal-redhat — APPROVED** [review]
LGTM

**Comment by nishith-vihar** [comment]
There are 2 things. First one being in line no: 52 of nd_parent_test the self.test_name variable represents test case name+vol type. Is it possible to change it in a way that it holds only test case name?
Second one is that d_parent_test does not hold a test_name. I think its better to add a self.test_name variable so that it is helpful in naming the volume names being created inside the test case

**Comment by srijan-sivakumar** [comment]
@nishith-vihar will handle the nomenclature of test and volumes in a separate patch.

**Review by nishith-vihar — APPROVED** [review]
LGTM

**Pull request merged**
