### PR TITLE
[Lint Fix] Fixed some flake issues.

### PR DESCRIPTION
**Pull request by srijan-sivakumar**
Ran autopep8 and fixed some linting issues.

Updates: #58

Signed-off-by: srijan-sivakumar <ssivakum@redhat.com>

### CODE REVIEW

**Comment by nik-redhat** [comment]
Is it just an effort to fix few of the errors or all of them? As, I see lint check still failing 😅

**Comment by srijan-sivakumar** [comment]
> Is it just an effort to fix few of the errors or all of them? As, I see lint check still failing sweat_smile

Patience :p There have been a reduction in the number of failures. Taking care of the remaining files now.

**Comment by nik-redhat** [comment]
> > Is it just an effort to fix few of the errors or all of them? As, I see lint check still failing sweat_smile
> 
> Patience :p There has been a reduction in the number of failures. Taking care of the remaining files now.

Ohhh.....you should use the features available in GitHub 😂....and mark the PR as 'Draft'.

**Comment by srijan-sivakumar** [comment]
@nik-redhat Its green again :p

**Comment by nik-redhat** [comment]
> @nik-redhat Its green again :p

Badhai ho 🎉😂

**Review by nik-redhat — APPROVED** [review]

**Pull request merged**
