### PR TITLE
Migrated TC test_peer_detach

### PR DESCRIPTION
**Pull request by nik-redhat**
Migrated TC [test_peer_detach](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_peer_detach.py)
Also, added the ops `peer_probe_servers` and `peer_detach_servers`.
Updated the peer ops to follow the same pattern of params declaration, i.e, first the list/str of servers and then the node to perform the operation.

Fixes: #505 and Fixes: #480
Updates: #292 

Signed-off-by: nik-redhat <nladha@redhat.com>

### CODE REVIEW

**Comment by nik-redhat** [comment]
Test Case Output:
```
Summary:
+---------------+-------+--------------+
|    Category   | Cases | Pass Percent |
+---------------+-------+--------------+
| nonDisruptive |   0   |      0       |
|   Disruptive  |   1   |     0.0      |
|     Total     |   1   |     0.0      |
+---------------+-------+--------------+
Table:
 test_peer_detach
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|   Generic   |     FAIL    | 19.425578117370605 |
+-------------+-------------+--------------------+



Framework runtime : 27.34434413909912
```
Fails as expected, but the peers are now peer probed before the TC ends.

**Comment by srijan-sivakumar** [comment]
@nik-redhat will check the patch in nightly env with complete suite to verify.

**Comment by nik-redhat** [comment]
> @nik-redhat will check the patch in nightly env with complete suite to verify.

Yeah, that would be better.

**Comment by srijan-sivakumar** [comment]
```
Traceback (most recent call last):
  File "/usr/lib64/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib64/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/root/redant/core/test_runner.py", line 111, in _nd_worker_process
    cls._run_test(job_data)
  File "/root/redant/core/test_runner.py", line 202, in _run_test
    test_stats = runner_thread_obj.run_thread()
  File "/root/redant/core/runner_thread.py", line 30, in run_thread
    self.terminate_test_func()
  File "./tests/nd_parent_test.py", line 86, in terminate
    self.redant.peer_probe_servers(self.server_list, self.server_list[0])
  File "./common/ops/gluster_ops/peer_ops.py", line 82, in peer_probe_servers
    ret['msg'][0].rstrip('\n')) is None):
KeyError: 0
```

**Comment by srijan-sivakumar** [comment]
This fails at the very first test case...

**Comment by nik-redhat** [comment]
> This fails at the very first test case...

Which test case?

**Comment by srijan-sivakumar** [comment]
> > This fails at the very first test case...
> 
> Which test case?

I checked out this patch to run in the CI for complete suite, and it failed at the very first test case. I think the peering mechanism change is causing this failure. I do know that the test indicates a bug in gluster, but the change is sort of disrupting all tests.

**Comment by nik-redhat** [comment]
@srijan-sivakumar try a CI test now..

**Review by srijan-sivakumar — APPROVED** [review]
LGTM

**Pull request merged**
