### PR TITLE
Removed sp flag

### PR DESCRIPTION
**Pull request by aujjwal-redhat**
`sp` flag is removed from the Argument Parser. The same is handled using
a condition.

Fixes: #665

Signed-off-by: Ayush Ujjwal <aujjwal@redhat.com>

### CODE REVIEW

**Comment by aujjwal-redhat** [comment]
# Ran 2 tests:

### Test 1

```js
(redantenv) [root@servera redant]# python3 core/redant_main.py -c ../Utilities/conf.yaml -ll D -t tests/functional/glusterd/test_default_log_level_of_cli.py 
    ____  __________  ___    _   ________
   / __ \/ ____/ __ \/   |  / | / /_  __/
  / /_/ / __/ / / / / /| | /  |/ / / /   
 / _, _/ /___/ /_/ / ___ |/ /|  / / /    
/_/ |_/_____/_____/_/  |_/_/ |_/ /_/     
                                         

✔ Param Handling Success.
✔ Test List built
✔ Log dir creation successful.
✔ Environment setup successful.
✔ Running test case : vol_create_test-rep
✔ Running test case : vol_create_test-dist
✔ vol_create_test-dist Succeeded
✔ Running test case : test_default_log_level_of_cli-dist
✔ vol_create_test-rep Succeeded
✔ Running test case : test_default_log_level_of_cli-rep
✔ test_default_log_level_of_cli-rep Succeeded
✔ Running test case : vol_destroy_test-rep
✔ test_default_log_level_of_cli-dist Succeeded
✔ Running test case : vol_destroy_test-dist
✔ vol_destroy_test-rep Succeeded
✔ Running test case : vol_create_test-arb
✔ vol_destroy_test-dist Succeeded
✔ Running test case : vol_create_test-disp
✔ vol_create_test-arb Succeeded
✔ Running test case : test_default_log_level_of_cli-arb
✔ vol_create_test-disp Succeeded
✔ Running test case : test_default_log_level_of_cli-disp
✔ test_default_log_level_of_cli-arb Succeeded
✔ Running test case : vol_destroy_test-arb
✔ test_default_log_level_of_cli-disp Succeeded
✔ Running test case : vol_destroy_test-disp
✔ vol_destroy_test-disp Succeeded
✔ Running test case : vol_create_test-dist-rep
✔ vol_destroy_test-arb Succeeded
✔ Running test case : vol_create_test-dist-arb
✔ vol_create_test-dist-rep Succeeded
✔ Running test case : test_default_log_level_of_cli-dist-rep
✔ vol_create_test-dist-arb Succeeded
✔ Running test case : test_default_log_level_of_cli-dist-arb
✔ test_default_log_level_of_cli-dist-arb Succeeded
✔ Running test case : vol_destroy_test-dist-arb
✔ test_default_log_level_of_cli-dist-rep Succeeded
✔ Running test case : vol_destroy_test-dist-rep
✔ vol_destroy_test-dist-arb Succeeded
✔ Running test case : vol_create_test-dist-disp
✔ vol_destroy_test-dist-rep Succeeded
✔ vol_create_test-dist-disp Succeeded
✔ Running test case : test_default_log_level_of_cli-dist-disp
✔ test_default_log_level_of_cli-dist-disp Succeeded
✔ Running test case : vol_destroy_test-dist-disp
✔ vol_destroy_test-dist-disp Succeeded
Summary:
+---------------+-------+--------------+
|    Category   | Cases | Pass Percent |
+---------------+-------+--------------+
| nonDisruptive |   1   |    100.0     |
|   Disruptive  |   0   |      0       |
|     Total     |   1   |    100.0     |
+---------------+-------+--------------+
Table:
 vol_create_test
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|     dist    |     PASS    | 13.138871908187866 |
|     rep     |     PASS    | 13.160494089126587 |
|     arb     |     PASS    |  15.2787184715271  |
|     disp    |     PASS    | 10.573388576507568 |
|   dist-rep  |     PASS    | 19.420488834381104 |
|   dist-arb  |     PASS    | 15.030253410339355 |
|  dist-disp  |     PASS    | 10.723023653030396 |
+-------------+-------------+--------------------+

 test_default_log_level_of_cli
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|     rep     |     PASS    | 26.04642629623413  |
|     dist    |     PASS    | 26.936105251312256 |
|     arb     |     PASS    | 24.921074390411377 |
|     disp    |     PASS    | 26.320483446121216 |
|   dist-arb  |     PASS    | 35.330193281173706 |
|   dist-rep  |     PASS    | 35.40190887451172  |
|  dist-disp  |     PASS    | 24.68265724182129  |
+-------------+-------------+--------------------+

 vol_destroy_test
 
+-------------+-------------+--------------------+
| Volume Type | Test Result |  Time taken (sec)  |
+-------------+-------------+--------------------+
|     rep     |     PASS    | 15.091238498687744 |
|     dist    |     PASS    | 18.937992095947266 |
|     disp    |     PASS    | 13.087250232696533 |
|     arb     |     PASS    | 18.93041157722473  |
|   dist-arb  |     PASS    |  19.5893394947052  |
|   dist-rep  |     PASS    | 21.967530012130737 |
|  dist-disp  |     PASS    | 12.427124500274658 |
+-------------+-------------+--------------------+



Framework runtime : 243.2532868385315

✔ Tearing down successful.
```


### Test 2

```js
(redantenv) [root@servera redant]# python3 core/redant_main.py -c ../Utilities/conf.yaml -ll D -t tests/functional/glusterd/test_add_brick.py 
    ____  __________  ___    _   ________
   / __ \/ ____/ __ \/   |  / | / /_  __/
  / /_/ / __/ / / / / /| | /  |/ / / /   
 / _, _/ /___/ /_/ / ___ |/ /|  / / /    
/_/ |_/_____/_____/_/  |_/_/ |_/ /_/     
                                         

✔ Param Handling Success.
✔ Test List built
✔ Log dir creation successful.
✔ Environment setup successful.
✔ Running test case : test_add_brick-dist-rep
✔ test_add_brick-dist-rep Succeeded
Summary:
+---------------+-------+--------------+
|    Category   | Cases | Pass Percent |
+---------------+-------+--------------+
| nonDisruptive |   0   |      0       |
|   Disruptive  |   1   |    100.0     |
|     Total     |   1   |    100.0     |
+---------------+-------+--------------+
Table:
 test_add_brick
 
+-------------+-------------+-------------------+
| Volume Type | Test Result |  Time taken (sec) |
+-------------+-------------+-------------------+
|   dist-rep  |     PASS    | 51.80441069602966 |
+-------------+-------------+-------------------+



Framework runtime : 62.912362575531006

✔ Tearing down successful.
```

**Comment by nik-redhat** [comment]
Do check for a non-existent file/TC as well

**Comment by aujjwal-redhat** [comment]
> Do check for a non-existent file/TC as well

yeah actually checked that :
```js
(redantenv) [root@servera redant]# python3 core/redant_main.py -c ../Utilities/conf.yaml -ll D -t tests/functional/glusterd/test_enabling_glusterd_debug_mode.py
    ____  __________  ___    _   ________
   / __ \/ ____/ __ \/   |  / | / /_  __/
  / /_/ / __/ / / / / /| | /  |/ / / /   
 / _, _/ /___/ /_/ / ___ |/ /|  / / /    
/_/ |_/_____/_____/_/  |_/_/ |_/ /_/     
                                         

✔ Param Handling Success.
Trueilding test list
tests/functional/glusterd/test_enabling_glusterd_debug_mode.py

Traceback (most recent call last):
⠙ Building test list  File "core/redant_main.py", line 122, in <module>
    main()
  File "core/redant_main.py", line 88, in main
    TestListBuilder.create_test_dict(args.test_dir, excluded_tests,
  File "/home/MyWork/Redant/redant/core/test_list_builder.py", line 77, in create_test_dict
    test_flags = cls._get_test_module_info(test_case_path)
  File "/home/MyWork/Redant/redant/core/test_list_builder.py", line 217, in _get_test_module_info
    flags = str(extract_comments(tc_path, mime="text/x-python")[0])
  File "/usr/local/lib/python3.8/site-packages/comment_parser/comment_parser.py", line 78, in extract_comments
    with open(filename, 'r') as code:
FileNotFoundError: [Errno 2] No such file or directory: 'tests/functional/glusterd/test_enabling_glusterd_debug_mode.py'
```

**Review by nik-redhat — DISMISSED** [review]
Lgtm.

**Comment by nik-redhat** [comment]
But I will prefer to wait for @srijan-sivakumar review.

**Comment by aujjwal-redhat** [comment]
> But I will prefer to wait for @srijan-sivakumar review.

yeah true. : )

**Comment by srijan-sivakumar** [comment]
> > Do check for a non-existent file/TC as well
> 
> yeah actually checked that :
> 
> ```js
> (redantenv) [root@servera redant]# python3 core/redant_main.py -c ../Utilities/conf.yaml -ll D -t tests/functional/glusterd/test_enabling_glusterd_debug_mode.py
>     ____  __________  ___    _   ________
>    / __ \/ ____/ __ \/   |  / | / /_  __/
>   / /_/ / __/ / / / / /| | /  |/ / / /   
>  / _, _/ /___/ /_/ / ___ |/ /|  / / /    
> /_/ |_/_____/_____/_/  |_/_/ |_/ /_/     
>                                          
> 
> ✔ Param Handling Success.
> Trueilding test list
> tests/functional/glusterd/test_enabling_glusterd_debug_mode.py
> 
> Traceback (most recent call last):
> ⠙ Building test list  File "core/redant_main.py", line 122, in <module>
>     main()
>   File "core/redant_main.py", line 88, in main
>     TestListBuilder.create_test_dict(args.test_dir, excluded_tests,
>   File "/home/MyWork/Redant/redant/core/test_list_builder.py", line 77, in create_test_dict
>     test_flags = cls._get_test_module_info(test_case_path)
>   File "/home/MyWork/Redant/redant/core/test_list_builder.py", line 217, in _get_test_module_info
>     flags = str(extract_comments(tc_path, mime="text/x-python")[0])
>   File "/usr/local/lib/python3.8/site-packages/comment_parser/comment_parser.py", line 78, in extract_comments
>     with open(filename, 'r') as code:
> FileNotFoundError: [Errno 2] No such file or directory: 'tests/functional/glusterd/test_enabling_glusterd_debug_mode.py'
> ```

The change LGTM, but I think we can add a try-except block here to prevent this traceback to be dumped to the user. We can simply display File/dir access error and then also add the error we got from the exception being thrown.

**Comment by aujjwal-redhat** [comment]
> > > Do check for a non-existent file/TC as well
> > 
> > 
> > yeah actually checked that :
> > ```js
> > (redantenv) [root@servera redant]# python3 core/redant_main.py -c ../Utilities/conf.yaml -ll D -t tests/functional/glusterd/test_enabling_glusterd_debug_mode.py
> >     ____  __________  ___    _   ________
> >    / __ \/ ____/ __ \/   |  / | / /_  __/
> >   / /_/ / __/ / / / / /| | /  |/ / / /   
> >  / _, _/ /___/ /_/ / ___ |/ /|  / / /    
> > /_/ |_/_____/_____/_/  |_/_/ |_/ /_/     
> >                                          
> > 
> > ✔ Param Handling Success.
> > Trueilding test list
> > tests/functional/glusterd/test_enabling_glusterd_debug_mode.py
> > 
> > Traceback (most recent call last):
> > ⠙ Building test list  File "core/redant_main.py", line 122, in <module>
> >     main()
> >   File "core/redant_main.py", line 88, in main
> >     TestListBuilder.create_test_dict(args.test_dir, excluded_tests,
> >   File "/home/MyWork/Redant/redant/core/test_list_builder.py", line 77, in create_test_dict
> >     test_flags = cls._get_test_module_info(test_case_path)
> >   File "/home/MyWork/Redant/redant/core/test_list_builder.py", line 217, in _get_test_module_info
> >     flags = str(extract_comments(tc_path, mime="text/x-python")[0])
> >   File "/usr/local/lib/python3.8/site-packages/comment_parser/comment_parser.py", line 78, in extract_comments
> >     with open(filename, 'r') as code:
> > FileNotFoundError: [Errno 2] No such file or directory: 'tests/functional/glusterd/test_enabling_glusterd_debug_mode.py'
> > ```
> 
> The change LGTM, but I think we can add a try-except block here to prevent this traceback to be dumped to the user. We can simply display File/dir access error and then also add the error we got from the exception being thrown.

Ack

**Comment by aujjwal-redhat** [comment]
```js
(redantenv) [root@servera redant]# python3 core/redant_main.py -c ../Utilities/conf.yaml -ll D -t tests/functional/glusterd/test_this.py
    ____  __________  ___    _   ________
   / __ \/ ____/ __ \/   |  / | / /_  __/
  / /_/ / __/ / / / / /| | /  |/ / / /   
 / _, _/ /___/ /_/ / ___ |/ /|  / / /    
/_/ |_/_____/_____/_/  |_/_/ |_/ /_/     
                                         

✔ Param Handling Success.
Error: Can't find the file

✖ FileNotFoundError in test list builder
```

**Review by srijan-sivakumar — APPROVED** [review]
LGTM

**Pull request merged**
